apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      containers:
        - name: spark-app
          image: niroshan009/my-spark-app:latest
          ports:
            - containerPort: 4567